### ISSUE TITLE
Modal toggle not working properly

### ISSUE THREAD

**Issue by dalisoft** [c0bra/svelma#32] opened 2019-09-28 14:38 UTC
Link: https://c0bra.github.io/svelma/components/modal

Steps to reproduce:
1. Click Toggle
2. Close Modal by any way (x button, click to black bg, etc)
3. Click to Toggle again
4. See DevTools.

You will see log similar or exactly like this

```
Modal.svelte:18 Uncaught (in promise) TypeError: Cannot read property 'removeChild' of null
    at Object.e.$$.update (Modal.svelte:18)
    at gt (index.mjs:617)
    at mt (index.mjs:593)
```

**Comment by hmmhmmhm** [comment] 2019-10-03 07:27
```
<Modal 
    bind:active={active}
    onBody={false}>
...
</Modal>
```
The temporary solution is as follows,
give the option `onBody={false}` and it will be does not cause the error.

**Comment by dalisoft** [comment] 2019-10-03 07:31
Thanks, i just reported the issue for author of repo as this project is nice and great. 
I am still awaiting until Svelte becomes popular and getting a lot ecosystem plugins and features

**Comment by zakaria-chahboun** [comment] 2020-04-11 20:41
Yeah! still the same issue in 2020

**Comment by thijsrausch** [comment] 2020-09-25 14:16
Came across the same problem. You can also experience it on the [documentation page for the modal](https://c0bra.github.io/svelma/components/modal/).

In my case, the problem is caused by controlling the boolean for showing/hiding the modal in a parent component (I use the Svelte "createEventDispatcher"). So while the suggestion of @hmmhmmhm suppresses the error, it does not solve my problem. 

A solution would be to expose the close function to a user defined function. I know for a fact [react-bootstrap](https://react-bootstrap.github.io/components/modal/) has this (see: "onHide={handleClose}"). I'm willing to dig into this and propose a solution. Does the author accept PR's and if so, any requirements?

**Comment by c0bra** [comment] 2020-10-01 13:44
@Thijsrausch Yes I absolutely accept PRs; no requirements. I simply haven't had time to work on this project lately, unfortunately.

**Comment by abbychau** [comment] 2021-03-18 20:39
I made a new repo for it. https://github.com/abbychau/svelma2

Has modal toggle fixed and added Modal Card Component. using Svelte 3 and Rollup, etc, too.

**Comment by samal-rasmussen** [comment] 2021-04-25 16:08
It works now :D

**Comment by abbychau** [comment] 2021-04-26 04:59
@samal-rasmussen Thank you for reporting.
I am closing this now.

Feel free to reopen if any unexpected behaviors happen.

**Closed as completed** 2021-04-26 04:59 UTC
